name: Renovate
on: [workflow_dispatch]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.12.0
        with:
          configurationFile: .github/workflows/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
